### ISSUE TITLE
TypeError: require.extensions.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by MarkLTZ** [wo01/bitcore-lib-zcash#3]
Hi there,

running `gulp test` I have the following error:

```
/home/mark/zcash/bitcore-lib-zcash/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/mark/zcash/bitcore-lib-zcash/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/mark/zcash/bitcore-lib-zcash/node_modules/gulp-git/index.js:2:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mark/zcash/bitcore-lib-zcash/node_modules/bitcore-build-zcash/index.js:44:11)

```

Could you please check and fix it?

Thanks,
Mark

**Comment by wo01** [comment]
You need to use node.js v4.
But, I do not modify test cases. Threfore, gulp test fails.

**Comment by MarkLTZ** [comment]
Thanks,

I did some update to make it works with node v8 and also gulp browser now works, anyway tests are not updated to work with zcash this they still fail.

Do you have plans to update the test suite?
