### ISSUE TITLE
TypeError: "value" argument must not be a number

### ISSUE THREAD

**Issue by junzhli** [wo01/bitcore-lib-zcash#5]
I can't set up your version of Zcash Insight API service and it is stuck with the error thrown from this library.
Here is the step I followed:
```shell
$ # clone repo
$ git clone https://github.com/wo01/zcash.git
$ cd zcash
$ git checkout bitcore
$ # build patched version of zcash and launch zcashd to wait until it finishes blockchain synchronization
$ # create folder 'node' for insight-api service
$ mkdir node
$ cd node
$ npm install wo01/bitcore-node-zcash
$ ./node_modules/bitcore-node-zcash/bin/bitcore-node-zcash create node2
$ cd node2
$ ./node_modules/bitcore-node-zcash/bin/bitcore-node-zcash install wo01/insight-api-zcash
$ # copy/paste the following to bitcore-node.json
$ # {
$ #  "network": "livenet",
$ #  "port": 3001,
$ #  "services": [
$ #    "bitcoind",
$ #    "web"
$ #  ],
$ #  "servicesConfig": {
$ #   "bitcoind": {
$ #     "spawn": {
$ #        "datadir": "/home/ubuntu/.zcash", (full path of config file - zcash.conf where it created itself)
$ #       "exec": "/home/ubuntu/zcash/src/zcashd" (full path of zcashd where i built zcash from your source code)
$ #
$ #      }
$ #    },
$ #    "insight-api-zcash": {
$ #      "disableRateLimiter": true
$ #    }
$ #  }
$ #}
$ ../node_modules/bitcore-node-zcash/bin/bitcore-node-zcash start

And it throws this error after it launches a few minutes, even a few seconds
Somehow I am not sure the way I followed is correct. Is there something wrong here?

**Comment by junzhli** [comment]
Logging in details

    at Function.Buffer.from (buffer.js:186:11)
    at Address.toBuffer (/home/ubuntu/zcash/mynode4/node_modules/bitcore-lib-zcash/lib/address.js:463:24)
    at Address.toString (/home/ubuntu/zcash/mynode4/node_modules/bitcore-lib-zcash/lib/address.js:486:34)
    at TxController.transformInvTransaction (/home/ubuntu/zcash/mynode4/node_modules/insight-api-zcash/lib/transactions.js:203:21)
    at InsightAPI.transactionEventHandler (/home/ubuntu/zcash/mynode4/node_modules/insight-api-zcash/lib/index.js:279:34)
    at emitOne (events.js:116:13)
    at Bitcoin.emit (events.js:211:7)
    at Bitcoin._zmqTransactionHandler (/home/ubuntu/zcash/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)
    at exports.Socket.<anonymous> (/home/ubuntu/zcash/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:713:12)
    at emitThree (events.js:136:13)
[2019-01-31T03:52:53.777Z] error: TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:186:11)
    at Address.toBuffer (/home/ubuntu/zcash/mynode4/node_modules/bitcore-lib-zcash/lib/address.js:463:24)
    at Address.toString (/home/ubuntu/zcash/mynode4/node_modules/bitcore-lib-zcash/lib/address.js:486:34)
    at TxController.transformInvTransaction (/home/ubuntu/zcash/mynode4/node_modules/insight-api-zcash/lib/transactions.js:203:21)
    at InsightAPI.transactionEventHandler (/home/ubuntu/zcash/mynode4/node_modules/insight-api-zcash/lib/index.js:279:34)
    at emitOne (events.js:116:13)
    at Bitcoin.emit (events.js:211:7)
    at Bitcoin._zmqTransactionHandler (/home/ubuntu/zcash/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:639:10)
    at exports.Socket.<anonymous> (/home/ubuntu/zcash/node_modules/bitcore-node-zcash/lib/services/bitcoind.js:713:12)
    at emitThree (events.js:136:13)
[2019-01-31T03:52:53.777Z] info: Beginning shutdown
[2019-01-31T03:52:53.778Z] info: Stopping insight-api-zcash
[2019-01-31T03:52:53.778Z] info: Stopping web
[2019-01-31T03:52:53.778Z] info: Stopping bitcoind
[2019-01-31T03:52:54.166Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
[2019-01-31T03:52:54.166Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2019-01-31T03:52:54.666Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2019-01-31T03:52:54.667Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2019-01-31T03:52:54.667Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332

**Comment by wo01** [comment]
Thank you for your report.
I have fixed the bug.
